### ISSUE TITLE
spring 版本问题

### ISSUE THREAD

**Issue by kyne0116** [alexxiyang/shiro-redis#10]
在spring4.0.7.RELEASE下运行正常，切换到4.1.4.RELEASE发现如下异常：
Caused by: java.lang.ClassCastException: java.util.LinkedList cannot be cast to org.apache.shiro.session.Session
	at org.crazycake.shiro.RedisSessionDAO.getActiveSessions(RedisSessionDAO.java:66)
	at org.apache.shiro.session.mgt.DefaultSessionManager.getActiveSessions(DefaultSessionManager.java:244)
	at org.apache.shiro.session.mgt.AbstractValidatingSessionManager.validateSessions(AbstractValidatingSessionManager.java:276)
	at org.apache.shiro.session.mgt.quartz.QuartzSessionValidationJob.execute(QuartzSessionValidationJob.java:80)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:223)

**Comment by kyne0116** [comment]
作者默认有shiro_redis_session和shiro_redis_cache两个keyprefix，而我set了一摸一样的keyprefix导致问题，所以Issue已关闭，抱歉！
