### ISSUE TITLE
redis.clients.jedis.exceptions.JedisConnectionException: Unknown reply: 6

### ISSUE THREAD

**Issue by zzq392342084** [alexxiyang/shiro-redis#17]
有时候会报下面的错误，好像是redis的多线程使用问题，这个要怎么解决？
redis.clients.jedis.exceptions.JedisConnectionException: Unknown reply: 6
    at redis.clients.jedis.Protocol.process(Protocol.java:132)
    at redis.clients.jedis.Protocol.read(Protocol.java:191)
    at redis.clients.jedis.Connection.getBinaryBulkReply(Connection.java:195)
    at redis.clients.jedis.BinaryJedis.get(BinaryJedis.java:119)
    at org.crazycake.shiro.RedisManager.get(RedisManager.java:54)
    at org.crazycake.shiro.RedisSessionDAO.doReadSession(RedisSessionDAO.java:89)
    at org.apache.shiro.session.mgt.eis.AbstractSessionDAO.readSession(AbstractSessionDAO.java:168)
    at org.apache.shiro.session.mgt.DefaultSessionManager.retrieveSessionFromDataSource(DefaultSessionManager.java:236)

**Comment by TracyJian** [comment]
楼主解决了吗？

**Comment by alexxiyang** [comment]
@zzq392342084 可否告知如何重现？

**Comment by alexxiyang** [comment]
Question has been a long time
