### ISSUE TITLE
一样的实现

### ISSUE THREAD

**Issue by DR-YangLong** [alexxiyang/shiro-redis#6]
我在项目开发中也实现了shiro的redis集群，发现了simplesession序列化会有问题，因为此类属性基本带有transient修饰词，必须使用此类自己实现的readObject和writeObject方法，在性能和大小考虑小，我使用了原生方式，fst方式，fastjson方式，kryo方式实现。另外，一个redis带来了单点，必然会出现单点故障。

**Comment by alexxiyang** [comment]
@DR-YangLong 您好，关于单点问题，是否考虑过使用Redis Sentinel的Automatic failover?

**Comment by DR-YangLong** [comment]
我目前的环境使用redis的单机，想过主备切换，但是app端还是需要开发，开始想的解决方法是使用zookeeper实现自动切换，对外提供一个访问地址，现在换了工作，项目小，redis没有继续使用

**Comment by DR-YangLong** [comment]
我测试在支持JDK原生序列化的情况下，fst的速度是最快的，fastjson慢到不可接受，fastjson不太适合对象的序列化，另外我参考了oschina的kryo的池式实现写了差不多的序列化器，但是性能还是没有fst好。

**Comment by ahai1980** [comment]
Caused by: redis.clients.jedis.exceptions.JedisMovedDataException: MOVED 14966 127.0.0.1:9002
	at redis.clients.jedis.Protocol.processError(Protocol.java:108)
	at redis.clients.jedis.Protocol.process(Protocol.java:151)
	at redis.clients.jedis.Protocol.read(Protocol.java:205)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:297)
	at redis.clients.jedis.Connection.getBinaryBulkReply(Connection.java:216)
	at redis.clients.jedis.BinaryJedis.get(BinaryJedis.java:159)
	at org.crazycake.shiro.RedisManager.get(RedisManager.java:54)
	at org.crazycake.shiro.RedisSessionDAO.doReadSession(RedisSessionDAO.java:89)
	at org.apache.shiro.session.mgt.eis.AbstractSessionDAO.readSession(AbstractSessionDAO.java:168)
	at org.apache.shiro.session.mgt.DefaultSessionManager.retrieveSessionFromDataSource(DefaultSessionManager.java:236)
	at org.apache.shiro.session.mgt.DefaultSessionManager.retrieveSession(DefaultSessionManager.java:222)
	at org.apache.shiro.session.mgt.AbstractValidatingSessionManager.doGetSession(AbstractValidatingSessionManager.java:118)
	at org.apache.shiro.session.mgt.AbstractNativeSessionManager.lookupSession(AbstractNativeSessionManager.java:105)
	at org.apache.shiro.session.mgt.AbstractNativeSessionManager.getSession(AbstractNativeSessionManager.java:97)
	at org.apache.shiro.mgt.SessionsSecurityManager.getSession(SessionsSecurityManager.java:125)
	at org.apache.shiro.mgt.DefaultSecurityManager.resolveContextSession(DefaultSecurityManager.java:456)
	at org.apache.shiro.mgt.DefaultSecurityManager.resolveSession(DefaultSecurityManager.java:442)
	at org.apache.shiro.mgt.DefaultSecurityManager.createSubject(DefaultSecurityManager.java:338)
	at org.apache.shiro.subject.Subject$Builder.buildSubject(Subject.java:846)
	at org.apache.shiro.web.subject.WebSubject$Builder.buildWebSubject(WebSubject.java:148)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.createSubject(AbstractShiroFilter.java:292)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:359)
	... 39 more
